version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/satellite-app
      - JWT_SECRET=your_super_secret_jwt_key_here
    volumes:
      - ../backend:/app
      - ../uploads:/app/uploads
    depends_on:
      - mongo
    restart: unless-stopped

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
    restart: unless-stopped

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ../database/migrations:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_DATABASE=satellite-app
    restart: unless-stopped

  ml-service:
    build:
      context: ..
      dockerfile: docker/Dockerfile.ml
    ports:
      - "8000:8000"
    volumes:
      - ../ml_model:/app
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped

volumes:
  mongo_data: